# This is a config for E2B sandbox template.
# You can use template ID (8y5yeauk9hno5rwcq3n8) or template name (telos-nextjs-test-1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("telos-nextjs-test-1") # Sync sandbox
# sandbox = await AsyncSandbox.create("telos-nextjs-test-1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('telos-nextjs-test-1')

team_id = "234b6ea0-27e0-4b40-89fd-9001c8cf9a18"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "telos-nextjs-test-1"
template_id = "8y5yeauk9hno5rwcq3n8"
